// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: core/v1/core.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceRequest) Reset() {
	*x = GetPriceRequest{}
	mi := &file_core_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRequest) ProtoMessage() {}

func (x *GetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetPriceRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *GetPriceRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type GetPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	SpotPrice     float64                `protobuf:"fixed64,2,opt,name=spot_price,json=spotPrice,proto3" json:"spot_price,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Prices        *PriceDetails          `protobuf:"bytes,4,opt,name=prices,proto3" json:"prices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceResponse) Reset() {
	*x = GetPriceResponse{}
	mi := &file_core_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceResponse) ProtoMessage() {}

func (x *GetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceResponse.ProtoReflect.Descriptor instead.
func (*GetPriceResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *GetPriceResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *GetPriceResponse) GetSpotPrice() float64 {
	if x != nil {
		return x.SpotPrice
	}
	return 0
}

func (x *GetPriceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetPriceResponse) GetPrices() *PriceDetails {
	if x != nil {
		return x.Prices
	}
	return nil
}

type PriceDetails struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BuyPrice         float64                `protobuf:"fixed64,1,opt,name=buy_price,json=buyPrice,proto3" json:"buy_price,omitempty"`
	SellPrice        float64                `protobuf:"fixed64,2,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	Spread           float64                `protobuf:"fixed64,3,opt,name=spread,proto3" json:"spread,omitempty"`
	BuyFee           float64                `protobuf:"fixed64,4,opt,name=buy_fee,json=buyFee,proto3" json:"buy_fee,omitempty"`
	SellFee          float64                `protobuf:"fixed64,5,opt,name=sell_fee,json=sellFee,proto3" json:"sell_fee,omitempty"`
	BuyFeePercent    float64                `protobuf:"fixed64,6,opt,name=buy_fee_percent,json=buyFeePercent,proto3" json:"buy_fee_percent,omitempty"`
	SellFeePercent   float64                `protobuf:"fixed64,7,opt,name=sell_fee_percent,json=sellFeePercent,proto3" json:"sell_fee_percent,omitempty"`
	BuyPriceWithFee  float64                `protobuf:"fixed64,8,opt,name=buy_price_with_fee,json=buyPriceWithFee,proto3" json:"buy_price_with_fee,omitempty"`
	SellPriceWithFee float64                `protobuf:"fixed64,9,opt,name=sell_price_with_fee,json=sellPriceWithFee,proto3" json:"sell_price_with_fee,omitempty"`
	BuyPremium       float64                `protobuf:"fixed64,10,opt,name=buy_premium,json=buyPremium,proto3" json:"buy_premium,omitempty"`
	SellDiscount     float64                `protobuf:"fixed64,11,opt,name=sell_discount,json=sellDiscount,proto3" json:"sell_discount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PriceDetails) Reset() {
	*x = PriceDetails{}
	mi := &file_core_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceDetails) ProtoMessage() {}

func (x *PriceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceDetails.ProtoReflect.Descriptor instead.
func (*PriceDetails) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{2}
}

func (x *PriceDetails) GetBuyPrice() float64 {
	if x != nil {
		return x.BuyPrice
	}
	return 0
}

func (x *PriceDetails) GetSellPrice() float64 {
	if x != nil {
		return x.SellPrice
	}
	return 0
}

func (x *PriceDetails) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *PriceDetails) GetBuyFee() float64 {
	if x != nil {
		return x.BuyFee
	}
	return 0
}

func (x *PriceDetails) GetSellFee() float64 {
	if x != nil {
		return x.SellFee
	}
	return 0
}

func (x *PriceDetails) GetBuyFeePercent() float64 {
	if x != nil {
		return x.BuyFeePercent
	}
	return 0
}

func (x *PriceDetails) GetSellFeePercent() float64 {
	if x != nil {
		return x.SellFeePercent
	}
	return 0
}

func (x *PriceDetails) GetBuyPriceWithFee() float64 {
	if x != nil {
		return x.BuyPriceWithFee
	}
	return 0
}

func (x *PriceDetails) GetSellPriceWithFee() float64 {
	if x != nil {
		return x.SellPriceWithFee
	}
	return 0
}

func (x *PriceDetails) GetBuyPremium() float64 {
	if x != nil {
		return x.BuyPremium
	}
	return 0
}

func (x *PriceDetails) GetSellDiscount() float64 {
	if x != nil {
		return x.SellDiscount
	}
	return 0
}

type CalculatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weight        float64                `protobuf:"fixed64,1,opt,name=weight,proto3" json:"weight,omitempty"`
	WeightUnit    string                 `protobuf:"bytes,2,opt,name=weight_unit,json=weightUnit,proto3" json:"weight_unit,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePriceRequest) Reset() {
	*x = CalculatePriceRequest{}
	mi := &file_core_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceRequest) ProtoMessage() {}

func (x *CalculatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceRequest.ProtoReflect.Descriptor instead.
func (*CalculatePriceRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *CalculatePriceRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CalculatePriceRequest) GetWeightUnit() string {
	if x != nil {
		return x.WeightUnit
	}
	return ""
}

func (x *CalculatePriceRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CalculatePriceRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CalculatePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Weight        float64                `protobuf:"fixed64,3,opt,name=weight,proto3" json:"weight,omitempty"`
	WeightUnit    string                 `protobuf:"bytes,4,opt,name=weight_unit,json=weightUnit,proto3" json:"weight_unit,omitempty"`
	SpotPrice     float64                `protobuf:"fixed64,5,opt,name=spot_price,json=spotPrice,proto3" json:"spot_price,omitempty"`
	BasePrice     float64                `protobuf:"fixed64,6,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	Fee           float64                `protobuf:"fixed64,7,opt,name=fee,proto3" json:"fee,omitempty"`
	FeePercent    float64                `protobuf:"fixed64,8,opt,name=fee_percent,json=feePercent,proto3" json:"fee_percent,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,9,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePriceResponse) Reset() {
	*x = CalculatePriceResponse{}
	mi := &file_core_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceResponse) ProtoMessage() {}

func (x *CalculatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceResponse.ProtoReflect.Descriptor instead.
func (*CalculatePriceResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *CalculatePriceResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CalculatePriceResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CalculatePriceResponse) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CalculatePriceResponse) GetWeightUnit() string {
	if x != nil {
		return x.WeightUnit
	}
	return ""
}

func (x *CalculatePriceResponse) GetSpotPrice() float64 {
	if x != nil {
		return x.SpotPrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetBasePrice() float64 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetFee() float64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *CalculatePriceResponse) GetFeePercent() float64 {
	if x != nil {
		return x.FeePercent
	}
	return 0
}

func (x *CalculatePriceResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type GetSpotPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpotPriceRequest) Reset() {
	*x = GetSpotPriceRequest{}
	mi := &file_core_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpotPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpotPriceRequest) ProtoMessage() {}

func (x *GetSpotPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpotPriceRequest.ProtoReflect.Descriptor instead.
func (*GetSpotPriceRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{5}
}

type GetSpotPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpotPrice     float64                `protobuf:"fixed64,1,opt,name=spot_price,json=spotPrice,proto3" json:"spot_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpotPriceResponse) Reset() {
	*x = GetSpotPriceResponse{}
	mi := &file_core_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpotPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpotPriceResponse) ProtoMessage() {}

func (x *GetSpotPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpotPriceResponse.ProtoReflect.Descriptor instead.
func (*GetSpotPriceResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *GetSpotPriceResponse) GetSpotPrice() float64 {
	if x != nil {
		return x.SpotPrice
	}
	return 0
}

var File_core_v1_core_proto protoreflect.FileDescriptor

const file_core_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x12core/v1/core.proto\x12\acore.v1\"%\n" +
	"\x0fGetPriceRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\"\x90\x01\n" +
	"\x10GetPriceResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"spot_price\x18\x02 \x01(\x01R\tspotPrice\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12-\n" +
	"\x06prices\x18\x04 \x01(\v2\x15.core.v1.PriceDetailsR\x06prices\"\x8a\x03\n" +
	"\fPriceDetails\x12\x1b\n" +
	"\tbuy_price\x18\x01 \x01(\x01R\bbuyPrice\x12\x1d\n" +
	"\n" +
	"sell_price\x18\x02 \x01(\x01R\tsellPrice\x12\x16\n" +
	"\x06spread\x18\x03 \x01(\x01R\x06spread\x12\x17\n" +
	"\abuy_fee\x18\x04 \x01(\x01R\x06buyFee\x12\x19\n" +
	"\bsell_fee\x18\x05 \x01(\x01R\asellFee\x12&\n" +
	"\x0fbuy_fee_percent\x18\x06 \x01(\x01R\rbuyFeePercent\x12(\n" +
	"\x10sell_fee_percent\x18\a \x01(\x01R\x0esellFeePercent\x12+\n" +
	"\x12buy_price_with_fee\x18\b \x01(\x01R\x0fbuyPriceWithFee\x12-\n" +
	"\x13sell_price_with_fee\x18\t \x01(\x01R\x10sellPriceWithFee\x12\x1f\n" +
	"\vbuy_premium\x18\n" +
	" \x01(\x01R\n" +
	"buyPremium\x12#\n" +
	"\rsell_discount\x18\v \x01(\x01R\fsellDiscount\"x\n" +
	"\x15CalculatePriceRequest\x12\x16\n" +
	"\x06weight\x18\x01 \x01(\x01R\x06weight\x12\x1f\n" +
	"\vweight_unit\x18\x02 \x01(\tR\n" +
	"weightUnit\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\x8b\x02\n" +
	"\x16CalculatePriceResponse\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x01R\x06weight\x12\x1f\n" +
	"\vweight_unit\x18\x04 \x01(\tR\n" +
	"weightUnit\x12\x1d\n" +
	"\n" +
	"spot_price\x18\x05 \x01(\x01R\tspotPrice\x12\x1d\n" +
	"\n" +
	"base_price\x18\x06 \x01(\x01R\tbasePrice\x12\x10\n" +
	"\x03fee\x18\a \x01(\x01R\x03fee\x12\x1f\n" +
	"\vfee_percent\x18\b \x01(\x01R\n" +
	"feePercent\x12\x1f\n" +
	"\vtotal_price\x18\t \x01(\x01R\n" +
	"totalPrice\"\x15\n" +
	"\x13GetSpotPriceRequest\"5\n" +
	"\x14GetSpotPriceResponse\x12\x1d\n" +
	"\n" +
	"spot_price\x18\x01 \x01(\x01R\tspotPrice2\xeb\x01\n" +
	"\bGoldCore\x12?\n" +
	"\bGetPrice\x12\x18.core.v1.GetPriceRequest\x1a\x19.core.v1.GetPriceResponse\x12Q\n" +
	"\x0eCalculatePrice\x12\x1e.core.v1.CalculatePriceRequest\x1a\x1f.core.v1.CalculatePriceResponse\x12K\n" +
	"\fGetSpotPrice\x12\x1c.core.v1.GetSpotPriceRequest\x1a\x1d.core.v1.GetSpotPriceResponseB.Z,github.com/jupiter/gold-proto/core/v1;corev1b\x06proto3"

var (
	file_core_v1_core_proto_rawDescOnce sync.Once
	file_core_v1_core_proto_rawDescData []byte
)

func file_core_v1_core_proto_rawDescGZIP() []byte {
	file_core_v1_core_proto_rawDescOnce.Do(func() {
		file_core_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_core_proto_rawDesc), len(file_core_v1_core_proto_rawDesc)))
	})
	return file_core_v1_core_proto_rawDescData
}

var file_core_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_core_v1_core_proto_goTypes = []any{
	(*GetPriceRequest)(nil),        // 0: core.v1.GetPriceRequest
	(*GetPriceResponse)(nil),       // 1: core.v1.GetPriceResponse
	(*PriceDetails)(nil),           // 2: core.v1.PriceDetails
	(*CalculatePriceRequest)(nil),  // 3: core.v1.CalculatePriceRequest
	(*CalculatePriceResponse)(nil), // 4: core.v1.CalculatePriceResponse
	(*GetSpotPriceRequest)(nil),    // 5: core.v1.GetSpotPriceRequest
	(*GetSpotPriceResponse)(nil),   // 6: core.v1.GetSpotPriceResponse
}
var file_core_v1_core_proto_depIdxs = []int32{
	2, // 0: core.v1.GetPriceResponse.prices:type_name -> core.v1.PriceDetails
	0, // 1: core.v1.GoldCore.GetPrice:input_type -> core.v1.GetPriceRequest
	3, // 2: core.v1.GoldCore.CalculatePrice:input_type -> core.v1.CalculatePriceRequest
	5, // 3: core.v1.GoldCore.GetSpotPrice:input_type -> core.v1.GetSpotPriceRequest
	1, // 4: core.v1.GoldCore.GetPrice:output_type -> core.v1.GetPriceResponse
	4, // 5: core.v1.GoldCore.CalculatePrice:output_type -> core.v1.CalculatePriceResponse
	6, // 6: core.v1.GoldCore.GetSpotPrice:output_type -> core.v1.GetSpotPriceResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_v1_core_proto_init() }
func file_core_v1_core_proto_init() {
	if File_core_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_core_proto_rawDesc), len(file_core_v1_core_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_core_proto_goTypes,
		DependencyIndexes: file_core_v1_core_proto_depIdxs,
		MessageInfos:      file_core_v1_core_proto_msgTypes,
	}.Build()
	File_core_v1_core_proto = out.File
	file_core_v1_core_proto_goTypes = nil
	file_core_v1_core_proto_depIdxs = nil
}
